/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/apis/vms/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExternalVms implements ExternalVmInterface
type FakeExternalVms struct {
	Fake *FakeVmsV1alpha1
	ns   string
}

var externalvmsResource = schema.GroupVersionResource{Group: "vms.kubevirt.io", Version: "v1alpha1", Resource: "externalvms"}

var externalvmsKind = schema.GroupVersionKind{Group: "vms.kubevirt.io", Version: "v1alpha1", Kind: "ExternalVm"}

// Get takes name of the externalVm, and returns the corresponding externalVm object, and an error if there is any.
func (c *FakeExternalVms) Get(name string, options v1.GetOptions) (result *v1alpha1.ExternalVm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externalvmsResource, c.ns, name), &v1alpha1.ExternalVm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalVm), err
}

// List takes label and field selectors, and returns the list of ExternalVms that match those selectors.
func (c *FakeExternalVms) List(opts v1.ListOptions) (result *v1alpha1.ExternalVmList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externalvmsResource, externalvmsKind, c.ns, opts), &v1alpha1.ExternalVmList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExternalVmList{ListMeta: obj.(*v1alpha1.ExternalVmList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExternalVmList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalVms.
func (c *FakeExternalVms) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externalvmsResource, c.ns, opts))

}

// Create takes the representation of a externalVm and creates it.  Returns the server's representation of the externalVm, and an error, if there is any.
func (c *FakeExternalVms) Create(externalVm *v1alpha1.ExternalVm) (result *v1alpha1.ExternalVm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externalvmsResource, c.ns, externalVm), &v1alpha1.ExternalVm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalVm), err
}

// Update takes the representation of a externalVm and updates it. Returns the server's representation of the externalVm, and an error, if there is any.
func (c *FakeExternalVms) Update(externalVm *v1alpha1.ExternalVm) (result *v1alpha1.ExternalVm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externalvmsResource, c.ns, externalVm), &v1alpha1.ExternalVm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalVm), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExternalVms) UpdateStatus(externalVm *v1alpha1.ExternalVm) (*v1alpha1.ExternalVm, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(externalvmsResource, "status", c.ns, externalVm), &v1alpha1.ExternalVm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalVm), err
}

// Delete takes name of the externalVm and deletes it. Returns an error if one occurs.
func (c *FakeExternalVms) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(externalvmsResource, c.ns, name), &v1alpha1.ExternalVm{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalVms) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externalvmsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExternalVmList{})
	return err
}

// Patch applies the patch and returns the patched externalVm.
func (c *FakeExternalVms) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExternalVm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externalvmsResource, c.ns, name, data, subresources...), &v1alpha1.ExternalVm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalVm), err
}
