/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/apis/vms/v1alpha1"
	scheme "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ExternalVmsGetter has a method to return a ExternalVmInterface.
// A group's client should implement this interface.
type ExternalVmsGetter interface {
	ExternalVms(namespace string) ExternalVmInterface
}

// ExternalVmInterface has methods to work with ExternalVm resources.
type ExternalVmInterface interface {
	Create(*v1alpha1.ExternalVm) (*v1alpha1.ExternalVm, error)
	Update(*v1alpha1.ExternalVm) (*v1alpha1.ExternalVm, error)
	UpdateStatus(*v1alpha1.ExternalVm) (*v1alpha1.ExternalVm, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ExternalVm, error)
	List(opts v1.ListOptions) (*v1alpha1.ExternalVmList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExternalVm, err error)
	ExternalVmExpansion
}

// externalVms implements ExternalVmInterface
type externalVms struct {
	client rest.Interface
	ns     string
}

// newExternalVms returns a ExternalVms
func newExternalVms(c *VmsV1alpha1Client, namespace string) *externalVms {
	return &externalVms{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the externalVm, and returns the corresponding externalVm object, and an error if there is any.
func (c *externalVms) Get(name string, options v1.GetOptions) (result *v1alpha1.ExternalVm, err error) {
	result = &v1alpha1.ExternalVm{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externalvms").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExternalVms that match those selectors.
func (c *externalVms) List(opts v1.ListOptions) (result *v1alpha1.ExternalVmList, err error) {
	result = &v1alpha1.ExternalVmList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externalvms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested externalVms.
func (c *externalVms) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("externalvms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a externalVm and creates it.  Returns the server's representation of the externalVm, and an error, if there is any.
func (c *externalVms) Create(externalVm *v1alpha1.ExternalVm) (result *v1alpha1.ExternalVm, err error) {
	result = &v1alpha1.ExternalVm{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("externalvms").
		Body(externalVm).
		Do().
		Into(result)
	return
}

// Update takes the representation of a externalVm and updates it. Returns the server's representation of the externalVm, and an error, if there is any.
func (c *externalVms) Update(externalVm *v1alpha1.ExternalVm) (result *v1alpha1.ExternalVm, err error) {
	result = &v1alpha1.ExternalVm{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("externalvms").
		Name(externalVm.Name).
		Body(externalVm).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *externalVms) UpdateStatus(externalVm *v1alpha1.ExternalVm) (result *v1alpha1.ExternalVm, err error) {
	result = &v1alpha1.ExternalVm{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("externalvms").
		Name(externalVm.Name).
		SubResource("status").
		Body(externalVm).
		Do().
		Into(result)
	return
}

// Delete takes name of the externalVm and deletes it. Returns an error if one occurs.
func (c *externalVms) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externalvms").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *externalVms) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externalvms").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched externalVm.
func (c *externalVms) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExternalVm, err error) {
	result = &v1alpha1.ExternalVm{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("externalvms").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
