
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.vms.kubevirt.io
  labels:
    api: vmware-proxy
    apiserver: "true"
spec:
  version: v1alpha1
  group: vms.kubevirt.io
  groupPriorityMinimum: 2000
  priority: 200
  service:
    name: vmware-proxy
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyakNDQXBhZ0F3SUJBZ0lKQVBLd09oMnBldDdaTUEwR0NTcUdTSWIzRFFFQkN3VUFNR3d4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLekFwQmdOVkJBTU1Jblp0ZDJGeVpTMXdjbTk0ZVMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3SGhjTk1Ua3dNakl5TVRBME9UTTRXaGNOTWpBd01qSXlNVEEwT1RNNFdqQnNNUXN3Q1FZRFZRUUcKRXdKMWJqRUxNQWtHQTFVRUNBd0NjM1F4Q2pBSUJnTlZCQWNNQVd3eENqQUlCZ05WQkFvTUFXOHhDekFKQmdOVgpCQXNNQW05MU1Tc3dLUVlEVlFRRERDSjJiWGRoY21VdGNISnZlSGt0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW1kcXI2MzIxK2s0bG1wU1kKVGZtelZLWXo2NnFOT2p3ckUrVEpZdmdGSjRSdzYzS3J4QnhHMzFBcFpsdkpZbncrUTBIU0YvUlZHMzd3TDFqYQpRd3BpaDRLcXdwTDlzZTQrU1hsdE9DOWJVL0NjZEE1Q0JLQ1J3NW5LK2hicm4wdFZTK29ia2FhQ2lwS0d3M3krCkszanQreWZYTGwyV244ZWhyMUJvY1RTWDMyaEpkNkVqVFpKMFF5S25IYlBQcGtYNFZEYXErbDVtNmlvOHRMeXUKYUZmeHl3TFYxbXAzYWdpMGxKM2tVYWV1dDFUbTB5QTZMV3NEYnlueTBBb1BaU3MrMU9YdWp0cGlINTJkdzVkTAozdkRwbmNxU0Fqc3EzU2EvZC9BSEkrUUV6dllIYkRYRkZ2d0NvYVpkUGRSRUVhcjN5QmM2RklUTi9EcVBwTEl4CnhpN2dxUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVWjdYZFc5VlJ1QVVyZisyeW15TXJmTUNvZXZjd0h3WUQKVlIwakJCZ3dGb0FVWjdYZFc5VlJ1QVVyZisyeW15TXJmTUNvZXZjd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFIald0RUtGeWhTL3BPM1JhSnMwRkFDUzJjMThrVFN5ajdKUzMrNTNNCnhwcHVuMnE2SVJJMERrTGhjUGJkVXRMTnN5STRZZWNDaE1FZjJEaUhCRUpDWUJUWHlBQ0RaYys0VHNDWVAvK0EKUzI0QU5rVmZLejFUZXVzVUwzU2ZESG1hVnRNRTRRWnU1dEhlN0Z0RmJSbEhaRWtRWmNQQWJuTCs2T1F5MFUvdgpnb3pOd2tBUlJtYXNCZy9JRGczeWpmejZsYXQvMGdEZWVTZllzQ0drTW83b2thVEsxWFB2L29CbUFjRWlibHRICmYvbWllQmFXdmxqb0gwbEJuV21xbjhBR25wczNSMnRzVU82bXFRdDc3amhHR3hOQVNRWThEY0JiOUVxbGNBSU4KWGJZNUdReUY5WnR2ek40cC82dG83bWFrWFdQOG5jNHhKdk9FdFpaZ0FlZ1JDZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: v1
kind: Service
metadata:
  name: vmware-proxy
  namespace: default
  labels:
    api: vmware-proxy
    apiserver: "true"
spec:
  type: ExternalName
  externalName: "10.0.2.2"
  ports:
  - port: 443
    protocol: TCP
