/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vmsv1alpha1 "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/apis/vms/v1alpha1"
	clientset "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/client/listers_generated/vms/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ExternalVmInformer provides access to a shared informer and lister for
// ExternalVms.
type ExternalVmInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ExternalVmLister
}

type externalVmInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExternalVmInformer constructs a new informer for ExternalVm type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExternalVmInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExternalVmInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExternalVmInformer constructs a new informer for ExternalVm type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExternalVmInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmsV1alpha1().ExternalVms(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmsV1alpha1().ExternalVms(namespace).Watch(options)
			},
		},
		&vmsv1alpha1.ExternalVm{},
		resyncPeriod,
		indexers,
	)
}

func (f *externalVmInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExternalVmInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *externalVmInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vmsv1alpha1.ExternalVm{}, f.defaultInformer)
}

func (f *externalVmInformer) Lister() v1alpha1.ExternalVmLister {
	return v1alpha1.NewExternalVmLister(f.Informer().GetIndexer())
}
