apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: provider-operator
  template:
    metadata:
      labels:
        name: provider-operator
    spec:
      serviceAccountName: provider-operator
      containers:
        - name: provider-operator
          # Replace this with the built image name
          image: quay.io/pkliczewski/provider-operator
          command:
          - provider-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "provider-operator"
