// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	vms "github.com/pkliczewski/provider-operators/apiserver-vmware/pkg/apis/vms"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ExternalVm)(nil), (*vms.ExternalVm)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalVm_To_vms_ExternalVm(a.(*ExternalVm), b.(*vms.ExternalVm), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vms.ExternalVm)(nil), (*ExternalVm)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vms_ExternalVm_To_v1alpha1_ExternalVm(a.(*vms.ExternalVm), b.(*ExternalVm), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalVmList)(nil), (*vms.ExternalVmList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalVmList_To_vms_ExternalVmList(a.(*ExternalVmList), b.(*vms.ExternalVmList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vms.ExternalVmList)(nil), (*ExternalVmList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vms_ExternalVmList_To_v1alpha1_ExternalVmList(a.(*vms.ExternalVmList), b.(*ExternalVmList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalVmSpec)(nil), (*vms.ExternalVmSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalVmSpec_To_vms_ExternalVmSpec(a.(*ExternalVmSpec), b.(*vms.ExternalVmSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vms.ExternalVmSpec)(nil), (*ExternalVmSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vms_ExternalVmSpec_To_v1alpha1_ExternalVmSpec(a.(*vms.ExternalVmSpec), b.(*ExternalVmSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalVmStatus)(nil), (*vms.ExternalVmStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalVmStatus_To_vms_ExternalVmStatus(a.(*ExternalVmStatus), b.(*vms.ExternalVmStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vms.ExternalVmStatus)(nil), (*ExternalVmStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vms_ExternalVmStatus_To_v1alpha1_ExternalVmStatus(a.(*vms.ExternalVmStatus), b.(*ExternalVmStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalVmStatusStrategy)(nil), (*vms.ExternalVmStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalVmStatusStrategy_To_vms_ExternalVmStatusStrategy(a.(*ExternalVmStatusStrategy), b.(*vms.ExternalVmStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vms.ExternalVmStatusStrategy)(nil), (*ExternalVmStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vms_ExternalVmStatusStrategy_To_v1alpha1_ExternalVmStatusStrategy(a.(*vms.ExternalVmStatusStrategy), b.(*ExternalVmStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalVmStrategy)(nil), (*vms.ExternalVmStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalVmStrategy_To_vms_ExternalVmStrategy(a.(*ExternalVmStrategy), b.(*vms.ExternalVmStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vms.ExternalVmStrategy)(nil), (*ExternalVmStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vms_ExternalVmStrategy_To_v1alpha1_ExternalVmStrategy(a.(*vms.ExternalVmStrategy), b.(*ExternalVmStrategy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ExternalVm_To_vms_ExternalVm(in *ExternalVm, out *vms.ExternalVm, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ExternalVmSpec_To_vms_ExternalVmSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ExternalVmStatus_To_vms_ExternalVmStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ExternalVm_To_vms_ExternalVm is an autogenerated conversion function.
func Convert_v1alpha1_ExternalVm_To_vms_ExternalVm(in *ExternalVm, out *vms.ExternalVm, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalVm_To_vms_ExternalVm(in, out, s)
}

func autoConvert_vms_ExternalVm_To_v1alpha1_ExternalVm(in *vms.ExternalVm, out *ExternalVm, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_vms_ExternalVmSpec_To_v1alpha1_ExternalVmSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_vms_ExternalVmStatus_To_v1alpha1_ExternalVmStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_vms_ExternalVm_To_v1alpha1_ExternalVm is an autogenerated conversion function.
func Convert_vms_ExternalVm_To_v1alpha1_ExternalVm(in *vms.ExternalVm, out *ExternalVm, s conversion.Scope) error {
	return autoConvert_vms_ExternalVm_To_v1alpha1_ExternalVm(in, out, s)
}

func autoConvert_v1alpha1_ExternalVmList_To_vms_ExternalVmList(in *ExternalVmList, out *vms.ExternalVmList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]vms.ExternalVm)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ExternalVmList_To_vms_ExternalVmList is an autogenerated conversion function.
func Convert_v1alpha1_ExternalVmList_To_vms_ExternalVmList(in *ExternalVmList, out *vms.ExternalVmList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalVmList_To_vms_ExternalVmList(in, out, s)
}

func autoConvert_vms_ExternalVmList_To_v1alpha1_ExternalVmList(in *vms.ExternalVmList, out *ExternalVmList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ExternalVm)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_vms_ExternalVmList_To_v1alpha1_ExternalVmList is an autogenerated conversion function.
func Convert_vms_ExternalVmList_To_v1alpha1_ExternalVmList(in *vms.ExternalVmList, out *ExternalVmList, s conversion.Scope) error {
	return autoConvert_vms_ExternalVmList_To_v1alpha1_ExternalVmList(in, out, s)
}

func autoConvert_v1alpha1_ExternalVmSpec_To_vms_ExternalVmSpec(in *ExternalVmSpec, out *vms.ExternalVmSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ExternalVmSpec_To_vms_ExternalVmSpec is an autogenerated conversion function.
func Convert_v1alpha1_ExternalVmSpec_To_vms_ExternalVmSpec(in *ExternalVmSpec, out *vms.ExternalVmSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalVmSpec_To_vms_ExternalVmSpec(in, out, s)
}

func autoConvert_vms_ExternalVmSpec_To_v1alpha1_ExternalVmSpec(in *vms.ExternalVmSpec, out *ExternalVmSpec, s conversion.Scope) error {
	return nil
}

// Convert_vms_ExternalVmSpec_To_v1alpha1_ExternalVmSpec is an autogenerated conversion function.
func Convert_vms_ExternalVmSpec_To_v1alpha1_ExternalVmSpec(in *vms.ExternalVmSpec, out *ExternalVmSpec, s conversion.Scope) error {
	return autoConvert_vms_ExternalVmSpec_To_v1alpha1_ExternalVmSpec(in, out, s)
}

func autoConvert_v1alpha1_ExternalVmStatus_To_vms_ExternalVmStatus(in *ExternalVmStatus, out *vms.ExternalVmStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ExternalVmStatus_To_vms_ExternalVmStatus is an autogenerated conversion function.
func Convert_v1alpha1_ExternalVmStatus_To_vms_ExternalVmStatus(in *ExternalVmStatus, out *vms.ExternalVmStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalVmStatus_To_vms_ExternalVmStatus(in, out, s)
}

func autoConvert_vms_ExternalVmStatus_To_v1alpha1_ExternalVmStatus(in *vms.ExternalVmStatus, out *ExternalVmStatus, s conversion.Scope) error {
	return nil
}

// Convert_vms_ExternalVmStatus_To_v1alpha1_ExternalVmStatus is an autogenerated conversion function.
func Convert_vms_ExternalVmStatus_To_v1alpha1_ExternalVmStatus(in *vms.ExternalVmStatus, out *ExternalVmStatus, s conversion.Scope) error {
	return autoConvert_vms_ExternalVmStatus_To_v1alpha1_ExternalVmStatus(in, out, s)
}

func autoConvert_v1alpha1_ExternalVmStatusStrategy_To_vms_ExternalVmStatusStrategy(in *ExternalVmStatusStrategy, out *vms.ExternalVmStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_ExternalVmStatusStrategy_To_vms_ExternalVmStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ExternalVmStatusStrategy_To_vms_ExternalVmStatusStrategy(in *ExternalVmStatusStrategy, out *vms.ExternalVmStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalVmStatusStrategy_To_vms_ExternalVmStatusStrategy(in, out, s)
}

func autoConvert_vms_ExternalVmStatusStrategy_To_v1alpha1_ExternalVmStatusStrategy(in *vms.ExternalVmStatusStrategy, out *ExternalVmStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_vms_ExternalVmStatusStrategy_To_v1alpha1_ExternalVmStatusStrategy is an autogenerated conversion function.
func Convert_vms_ExternalVmStatusStrategy_To_v1alpha1_ExternalVmStatusStrategy(in *vms.ExternalVmStatusStrategy, out *ExternalVmStatusStrategy, s conversion.Scope) error {
	return autoConvert_vms_ExternalVmStatusStrategy_To_v1alpha1_ExternalVmStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_ExternalVmStrategy_To_vms_ExternalVmStrategy(in *ExternalVmStrategy, out *vms.ExternalVmStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_ExternalVmStrategy_To_vms_ExternalVmStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ExternalVmStrategy_To_vms_ExternalVmStrategy(in *ExternalVmStrategy, out *vms.ExternalVmStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalVmStrategy_To_vms_ExternalVmStrategy(in, out, s)
}

func autoConvert_vms_ExternalVmStrategy_To_v1alpha1_ExternalVmStrategy(in *vms.ExternalVmStrategy, out *ExternalVmStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_vms_ExternalVmStrategy_To_v1alpha1_ExternalVmStrategy is an autogenerated conversion function.
func Convert_vms_ExternalVmStrategy_To_v1alpha1_ExternalVmStrategy(in *vms.ExternalVmStrategy, out *ExternalVmStrategy, s conversion.Scope) error {
	return autoConvert_vms_ExternalVmStrategy_To_v1alpha1_ExternalVmStrategy(in, out, s)
}
