// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVm":       schema_pkg_apis_kubevirt_v1alpha1_ExternalVm(ref),
		"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVmSpec":   schema_pkg_apis_kubevirt_v1alpha1_ExternalVmSpec(ref),
		"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVmStatus": schema_pkg_apis_kubevirt_v1alpha1_ExternalVmStatus(ref),
		"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProvider":       schema_pkg_apis_kubevirt_v1alpha1_VmProvider(ref),
		"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProviderSpec":   schema_pkg_apis_kubevirt_v1alpha1_VmProviderSpec(ref),
		"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProviderStatus": schema_pkg_apis_kubevirt_v1alpha1_VmProviderStatus(ref),
	}
}

func schema_pkg_apis_kubevirt_v1alpha1_ExternalVm(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ExternalVm is the Schema for the externalvms API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVmSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVmStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVmSpec", "github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.ExternalVmStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kubevirt_v1alpha1_ExternalVmSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ExternalVmSpec defines the desired state of ExternalVm",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubevirt_v1alpha1_ExternalVmStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ExternalVmStatus defines the observed state of ExternalVm",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubevirt_v1alpha1_VmProvider(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VmProvider is the Schema for the vmproviders API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProviderSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProviderStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProviderSpec", "github.com/pkliczewski/provider-operators/provider-operator/pkg/apis/kubevirt/v1alpha1.VmProviderStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kubevirt_v1alpha1_VmProviderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VmProviderSpec defines the desired state of VmProvider",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubevirt_v1alpha1_VmProviderStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VmProviderStatus defines the observed state of VmProvider",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
